name: CI

on:
  push:
    branches:
      - main

jobs:
  # 自動デプロイのためのビルド
  build-for-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Build app
        run: |
          REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          npm run build -- --deploy-url "/${REPOSITORY_NAME}/" --base-href "/${REPOSITORY_NAME}"
          cp -r dist/*/ docs/
          cp docs/index.html docs/404.html
      - name: Upload app to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@830e6a4f7c81743c52f3fed0ac67428feff9620a
        with:
          branch: gh-pages
          folder: docs/
